-- MistySoft Database Schema
-- Run this file first, then seeds/initial_data.sql
-- IMPORTANT: On shared hosting, select your database in phpMyAdmin before importing
-- Do NOT include CREATE DATABASE or USE statements

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS pricing_plans;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS content_blocks;

CREATE TABLE content_blocks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  block_key VARCHAR(50) NOT NULL UNIQUE,
  title VARCHAR(255) DEFAULT NULL,
  content JSON NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  short_description TEXT,
  description LONGTEXT,
  logo VARCHAR(255) DEFAULT NULL,
  images JSON DEFAULT NULL,
  website_url VARCHAR(500) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pricing_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(12,0) DEFAULT NULL,
  features JSON NOT NULL,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  is_custom TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  package VARCHAR(50) DEFAULT NULL,
  hosting VARCHAR(50) DEFAULT NULL,
  website_type VARCHAR(50) DEFAULT NULL,
  website_type_other VARCHAR(255) DEFAULT NULL,
  industry VARCHAR(50) DEFAULT NULL,
  industry_other VARCHAR(255) DEFAULT NULL,
  purpose VARCHAR(50) DEFAULT NULL,
  purpose_other VARCHAR(255) DEFAULT NULL,
  message TEXT,
  attachment_path VARCHAR(500) DEFAULT NULL,
  source VARCHAR(50) NOT NULL DEFAULT 'landing',
  ip_address VARCHAR(45) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
